FROM node:18

WORKDIR /opt/app

RUN npm install --global pm2

#ENV NODE_ENV development
 ENV NODE_ENV production

COPY package.json ./

COPY yarn.lock ./

RUN yarn --frozon-lockfile

COPY . /opt/app

RUN yarn run build

EXPOSE 3000

CMD [ "pm2-runtime", "npm", "--", "start" ]
