/* 22.11.10 수정: videoUrl 추가 */
/* 22.11.10 수정: 시간 12:00 PM으로 변경 */
import { Nft } from '@components/marketplace/nft/item/MarketplaceCard';

export interface cardDataPropsType {
  state: 'upcoming' | 'auction-start' | 'auction-ing' | 'closed' | 'buy-now' | 'offer-open' | 'offer-ing' | 'not-sale';
  myCollection: boolean;
  collectionName: string;
  productTitle: string;
  /* 22.11.21 수정: priceLabel 추가 */
  priceLabel?: string;
  price: string;
  imgUrl: string;
  videoUrl?: string;
  creatorName: string;
  likeCount: number;
  startTime?: string;
  endTime?: string;
  winnerName?: string;
  ownerName?: string;
  editionTotalNum?: number;
  editionNum?: number;
  type?: 'auction' | 'fixed'; // upcoming 일 때 옥션가/고정가를 나누는 타입
  bidders?: number; // bidders 명 수
  bidList?: BidListType[]; // bidding List
  secondAuction?: boolean; // 2차 판매시 여부
}

export interface BidListType {
  image?: string;
  name: string;
  time: string;
  price: string;
}

export const nftList: Nft[] = [
  {
    id: 1,
    type: "auction",
    videoUrl: "https://file.mir4global.com/nile/resources/video/life_sights_of_nile.mp4",
    title: "SON #1 New World",
    collection: {
      id: 1,
      title: "Sights of NILE(SON)",
      status: "ON SALE",
      creator: {
        id: 1,
        name: "Rokkan Kim",
        wallet: "0x00"
      }
    },
    owner: {
      id: 1,
      name: "Rokkan Kim",
      wallet: "0x00"
    },
    status: "upcoming",
    price: '1900',
    unitFormat: "WEMIX$",
    favorite: false,
    startDate: "2022-11-22 12:00 PM",
    creator: {
      id: 1,
      name: "creator",
      wallet: "0x00"
    },
    participants: 20
  },
]

export const nftCardData: cardDataPropsType[] = [
  {
    state: 'upcoming',
    myCollection: true,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '01 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    videoUrl: '/video/life_sights_of_nile_thumbnail.mp4',
    creatorName: 'Zeeha & Locho',
    likeCount: 1200,
    startTime: '2022-09-01 14:00',
    endTime: '2022-12-14 15:00',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidList: [
      {
        name: 'imsosadfefe',
        time: '7',
        price: '1400',
      },
      {
        image: 'url(https://picsum.photos/32/32/?image=1)',
        name: 'kingscross',
        time: '6',
        price: '1500',
      },
      {
        image: 'url(https://picsum.photos/32/32/?image=1)',
        name: 'Username',
        time: '3',
        price: '1600',
      },
    ],
  },
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '02 Hounslow WestHounslow WestHounslow WestHounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 90,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
  },
  {
    state: 'auction-ing',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '03 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 1200,
    startTime: '',
    endTime: '2022-09-01 14:00',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 12,
  },
  {
    state: 'closed',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '04 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 1000,
    startTime: '',
    endTime: '',
    winnerName: 'beeple_crap',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '05 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Final Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 2000,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '05 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Fixed Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 2000,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
    secondAuction: true,
  },
  {
    state: 'offer-open',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '06 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
    secondAuction: true,
  },
  {
    state: 'offer-ing',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '07 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
    secondAuction: true,
  },
  {
    state: 'not-sale',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: '08 Hounslow West',
    /* 22.11.21 수정: priceLabel 추가 */
    priceLabel: 'Starting Bid',
    price: '1200',
    imgUrl: '/temp/@temp_collection_lus.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
    secondAuction: true,
  },
];

// TODO : 11일 오픈 임시데이터 추가
/* 22.11.10 수정: 임시 데이터 수정 */
/* 22.11.17 수정: 11/22일 오픈 데이터로 수정 */
export const nftCardOpenData: cardDataPropsType[] = [
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #9 Arsenal',
    price: '750',
    imgUrl: '/temp/@temp_collection_lus_9.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
  },
  {
    state: 'auction-ing',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #141 Marble Arch',
    price: '1100',
    imgUrl: '/temp/@temp_collection_lus_141.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 7,
  },
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #30 Brixton',
    price: '1400',
    imgUrl: '/temp/@temp_collection_lus_30.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 7,
  },
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #9 Arsenal',
    price: '750',
    imgUrl: '/temp/@temp_collection_lus_9.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
  },
  {
    state: 'auction-ing',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #141 Marble Arch',
    price: '1100',
    imgUrl: '/temp/@temp_collection_lus_141.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 7,
  },
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'London Underground Station(LUS) 264 Genesis',
    productTitle: 'LUS #30 Brixton',
    price: '1400',
    imgUrl: '/temp/@temp_collection_lus_30.png',
    creatorName: 'Zeeha & Locho',
    likeCount: 0,
    startTime: '2022-11-22 15:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 7,
  },
];

export const tangledCardData: cardDataPropsType[] = [
  {
    state: 'buy-now',
    myCollection: true,
    collectionName: 'Tangled Timepieces',
    productTitle: '01 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '2022-09-01 14:00',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '02 Hounslow WestHounslow WestHounslow WestHounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '03 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '04 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: 'Tangled',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '05 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'Tangled',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '06 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'Tangled',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '07 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'Tangled',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'buy-now',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: '08 Hounslow West',
    price: '1200',
    imgUrl: '/temp/@temp_collection_tangled.png',
    creatorName: 'Tangled',
    likeCount: 999,
    startTime: '',
    endTime: '',
    winnerName: '',
    ownerName: 'Tangled',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
];

// TODO : 11일 오픈 임시데이터 추가
/* 22.11.10 수정: 임시 데이터 수정 */
export const tangledCardOpenData: cardDataPropsType[] = [
  {
    state: 'upcoming',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: 'Tangled Timepieces Luxury 79',
    price: '99',
    imgUrl: '/temp/@temp_collection_tangled_79.png',
    creatorName: 'Tangled',
    likeCount: 1200,
    startTime: '2022-12-01 12:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'upcoming',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: 'Tangled Timepieces Luxury 80',
    price: '99',
    imgUrl: '/temp/@temp_collection_tangled_80.png',
    creatorName: 'Tangled',
    likeCount: 1,
    startTime: '2022-12-01 12:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
  {
    state: 'upcoming',
    myCollection: false,
    collectionName: 'Tangled Timepieces',
    productTitle: 'Tangled Timepieces Luxury 167',
    price: '99',
    imgUrl: '/temp/@temp_collection_tangled_167.png',
    creatorName: 'Tangled',
    likeCount: 0,
    startTime: '2022-12-01 12:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
];

/* 22.11.10 수정: videoUrl 추가 */
export const storyCardData: cardDataPropsType[] = [
  {
    state: 'auction-start',
    myCollection: false,
    collectionName: 'Sights of NILE(SON)',
    productTitle: 'SON #1 New World',
    price: '1900',
    imgUrl: '/temp/@temp_collection_story.png',
    videoUrl: 'https://file.mir4global.com/nile/resources/video/life_sights_of_nile.mp4',
    creatorName: 'beeple_crap',
    likeCount: 1,
    /* 22일 오픈 스타트 시간 히든 */
    // startTime: '2022-11-22 12:00 PM',
    endTime: '',
    winnerName: 'beeple_crap',
    ownerName: 'beeple_crap',
    editionTotalNum: 10,
    editionNum: 1,
    bidders: 4,
  },
];

/* 22.11.10 수정: 임시 데이터 수정 */
export const snkrzCardData: cardDataPropsType[] = [
  {
    state: 'upcoming',
    myCollection: false,
    collectionName: 'Story3.0 NFT Project',
    productTitle: 'Story3.0 #1',
    price: '30',
    imgUrl: '/temp/@temp_collection_snkrz.png',
    creatorName: 'beeple_crap',
    likeCount: 0,
    startTime: '2022-11-00 12:00 PM',
    endTime: '',
    winnerName: '',
    ownerName: '',
    editionTotalNum: 10,
    editionNum: 1,
    type: 'fixed',
  },
];
