apiVersion: v1
kind: Service
metadata:
  name: nile-fe
  labels:
    run: nile-fe
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nile-fe
  type: ClusterIP
